import warnings
warnings.filterwarnings('ignore')

import time
import numpy as np
from typing import Tuple

try:
    # On Ascend 310B edge nodes, MindSpore Lite is the standard lightweight inference engine
    import mindspore_lite as mslite
except ImportError:
    raise ImportError("[ERROR] mindspore_lite is not installed in the current environment.")

class AscendEdgeInferencer:
    """
    Hardware-Accelerated Inference Engine for Huawei Ascend NPU.
    
    This class loads the compiled MindIR artifact and executes ultra-low latency 
    forward passes utilizing the Ascend 310B Neural Processing Unit (NPU).
    """
    def __init__(self, mindir_path: str, device_id: int = 0):
        """
        Initializes the Ascend runtime context and loads the static computational graph.
        """
        self.mindir_path = mindir_path
        self.device_id = device_id
        self._init_npu_context()
        self._build_model()

    def _init_npu_context(self):
        """Configures the hardware context to strictly utilize the Ascend NPU."""
        print(f"[INFO] Initializing Ascend Hardware Context on Device {self.device_id}...")
        self.context = mslite.Context()
        self.context.target = ["Ascend"]
        
        # Configure Ascend-specific hardware parameters (FP16 precision for throughput)
        self.context.ascend.device_id = self.device_id
        self.context.ascend.precision_mode = "enforce_fp16"

    def _build_model(self):
        """Compiles the MindIR artifact into the NPU execution graph."""
        print(f"[INFO] Loading and compiling MindIR artifact: {self.mindir_path}")
        self.model = mslite.Model()
        self.model.build_from_file(self.mindir_path, mslite.ModelType.MINDIR, self.context)
        print("[SUCCESS] Model successfully mapped to NPU memory.")

    def predict(self, vis_arr: np.ndarray, sonar_arr: np.ndarray, physio_arr: np.ndarray) -> np.ndarray:
        """
        Executes a synchronous forward pass on the NPU.
        
        Args:
            vis_arr: Visual sequence array [Batch, 16, 512]
            sonar_arr: Sonar sequence array [Batch, 16, 128]
            physio_arr: Physiological sequence array [Batch, 16, 64]
            
        Returns:
            np.ndarray: The predicted distress probabilities [Batch, 2]
        """
        # 1. Retrieve the statically allocated input tensors on the NPU
        inputs = self.model.get_inputs()
        
        # 2. Bind the preprocessed NumPy arrays to the NPU memory buffers
        inputs[0].set_data_from_numpy(vis_arr)
        inputs[1].set_data_from_numpy(sonar_arr)
        inputs[2].set_data_from_numpy(physio_arr)
        
        # 3. Execute Graph Inference
        start_time = time.time()
        outputs = self.model.predict(inputs)
        latency_ms = (time.time() - start_time) * 1000
        
        # 4. Extract results and compute Softmax for probabilities
        logits = outputs[0].get_data_to_numpy()
        # Softmax computation
        exp_logits = np.exp(logits - np.max(logits, axis=-1, keepdims=True))
        probabilities = exp_logits / np.sum(exp_logits, axis=-1, keepdims=True)
        
        return probabilities, latency_ms


# ==========================================
# Edge Profiling Module
# ==========================================
if __name__ == "__main__":
    print("[INFO] Commencing Ascend 310B NPU Inference Profiling...")
    
    # Path to the exported MindIR model (generated by export_mindir.py)
    model_path = "cadt_edge_model.mindir"
    
    try:
        # Initialize NPU Engine
        inferencer = AscendEdgeInferencer(mindir_path=model_path, device_id=0)
        
        # Simulate continuous edge streaming (e.g., 5 consecutive frames)
        for i in range(5):
            dummy_vis = np.random.randn(1, 16, 512).astype(np.float32)
            dummy_sonar = np.random.randn(1, 16, 128).astype(np.float32)
            dummy_physio = np.random.randn(1, 16, 64).astype(np.float32)
            
            probs, latency = inferencer.predict(dummy_vis, dummy_sonar, dummy_physio)
            
            print(f"  [Stream {i+1}] Latency: {latency:.2f} ms | Distress Probability: {probs[0][1]:.4f}")
            
    except Exception as e:
        print(f"[ERROR] Inference initialization failed. Ensure the .mindir exists and Ascend drivers are loaded. Details: {e}")